.segment "TEXTRESOURCES"

_00: .byte "   Der Zwerg keucht: ",$22,"Dunkelelfen...Rettet den K",$7e,"nig... der Prinz ist fort...",$22,". Er wird ohnm",$7d,"chtig. ",0
_01: .byte "   ",$22,"Ich danke Euch, nun finde ich allein zur",$7f,"ck. Seid gewarnt vor den Steint",$7f,"ren in den W",$7d,"nden. Es sind Eing",$7d,"nge, die mit dem richtigen Schl",$7f,"ssel aktiviert werden. Mein Team campierte einst neben einem und wurde ",$7f,"berfallen.",$22," Er dankt Euch erneut und zieht von dannen. ",0
_02: .byte "   ",$22,"Ich bin Armun, Sprecher des Clans. Nat",$7f,"rlich wissen wir ",$7f,"ber die Ausg",$7d,"nge dieser Hallen. Aber ich kann Euch in diesen unseren Stunden der Not nicht helfen. Solltet Ihr jedoch Willens sein, uns zu helfen..",$22," ",0
_03: .byte "   Armun beginnt: ",$22,"Unser Clan stammt von den Zwergen ab, die diese gro",$7c,"en Hallen erbauten. Hier lebten unsere Vorfahren in Frieden, bis Horden b",$7e,"ser Kreaturen sie in das Reich der Menschen und Elfen vertrieben.",$a,"    ",$22,"Dort ",$7f,"ber der Erde schwand unsere Anzahl, bis K",$7e,"nig Teirgoh unser Volk versammelte und uns in den Untergrund f",$7f,"hrte, auf der Suche nach unserer angestammten Heimat.",$a,"    ",$22,"Durch sein geheimes Wissen der k",$7e,"niglichen Familie fanden wir schlie",$7c,"lich diese aus Stein gehauenen Hallen. Sie waren riesig. Wir hatten nur einen kleinen Teil erkundet, bis wir in einem kleinen, abgeschlossenen Bereich, der mit einem Steinportal verziert war, kampieren mussten.",$a,"    ",$22,"Und w",$7d,"hrend alle schliefen, loderte magisches Licht um das Steinportal! Aus dem Licht griff uns eine Horde Dunkelelfen an. Sie wurden von einer Frau namens Shindia angef",$7f,"hrt.",$a,"    ",$22,"Wir k",$7d,"mpften gegen sie, doch waren wir geschw",$7d,"cht von der langen Reise. Auf beiden Seiten gab es schwere Verluste, doch schlie",$7c,"lich konnten wir sie zur",$7f,"ck in das Portal dr",$7d,"ngen, aus dem sie kamen.",$a,"    ",$22,"Wir haben bitter bezahlt. K",$7e,"nig Teirgoh wurde von einem vergifteten Dolch verwundet und liegt nun in endlosem Schlaf. Unser Kleriker kann ihn durch nichts erwecken. Prinz Keirgar, sein einziger Sohn, wurde von den Angreifern gefangen genommen. Ohne ein Mitglied der k",$7e,"niglichen Familie haben wir kein Wissen ",$7f,"ber die Ausg",$7d,"nge dieser Halle.",$a,"    ",$22,"Nun warten wir darauf, dass unser Kleriker unsere ",$7f,"berlebenden Krieger heilt. Dann werden wir versuchen, Prinz Keirgar zu befreien und Teirgoh zu r",$7d,"chen. Wir sind nur wenige, doch k",$7d,"mpfen wir lieber bis zum Tod, als unseren Prinzen den Dunkelelfen zu ",$7f,"berlassen.",$a,"    ",$22,"Au",$7c,"er nat",$7f,"rlich... Wenn Ihr den Prinzen befreit und zu uns zur",$7f,"ckbringt, w",$7f,"rde er Euch die Ausg",$7d,"nge dieser Halle enth",$7f,"llen. Ihr h",$7d,"ttet Eure Informationen und wir unseren Prinzen. Also, werdet Ihr uns helfen?",$22," ",0
_04: .byte "   Armuns Ausdruck wechselt von Hoffnung zu Entt",$7d,"uschung. ",$22,"Wie beda",$7f,"rlich dass Ihr uns nicht helfen k",$7e,"nnt. Viel Gl",$7f,"ck.",$22," ",0
_05: .byte "   Dankbar nimmt Armun Eure Hilfe an. Er gibt Euch ein Steinmedallion. ",$22,"Nehmt dies. Shindia lie",$7c," es im Kampf fallen. Es ist der Schl",$7f,"ssel, der das Portal ",$7e,"ffnet, durch das sie und ihre Horden kamen.",$a,"    ",$22,"Unsere Vorfahren bauten die Portale, um sich schnell von einem Ort zum anderen zu bewegen. Wenn man ein Portal mit dem richtigen Objekt ber",$7f,"hrt, wird es aktiviert. Wir w",$7d,"ren Shindia und ihren Dunkelelfen gefolgt, doch wir waren noch nicht bereit f",$7f,"r einen neuen Kampf.",$a,"    ",$22,"Die Alten nutzen diese m",$7d,"chtige Magie um Wissen zu erlangen. In Legenden ist von einem Orakel des Wissens die Rede. Der Schl",$7f,"ssel dazu sei eine machtvolle schwarze Kugel. Wird eine solche Kugel in das Orakel gelegt, wird die Macht freigesetzt.",$a,"    ",$22,"Unser Kleriker kann Eure Wunden heilen. Nehmt jedoch R",$7f,"cksicht, er hat schon die Wunden unserer Krieger geheilt und versucht, den K",$7e,"nig wiederzubeleben.",$22," ",0
_06: .byte "   Armun h",$7d,"lt inne. ",$22,"H",$7e,"rt, ein junger Zwergenkrieger w",$7f,"rde Euch gern helfen, den Prinzen zu finden. Lasst Ihr ihn mit Euch ziehen?",$22," ",0
_07: .byte "   Ein verletzter Zwerg liegt vor Euch, beinahe bewusstlos. ",0
_08: .byte "   Ein m",$7f,"der Zwergenkleriker gr",$7f,$7c,"t Euch. ",$22,"Wie kann ich Euch helfen?",$22," ",0
_09: .byte "   ",$22,"Wen soll ich wiedererwecken?",$22," ",0
_10: .byte "   Ein ersch",$7e,"pfter Zwergenkleriker reibt seine Augen. Er bittet Euch wiederzukommen, wenn er geruht hat. ",0
_11: .byte "   Nachdem er sich erholt hat, dankt Euch der Zwerg. ",$22,"Ich dachte schon, das Messer dieses Dunkelelfs h",$7d,"tte mich erledigt. Unser K",$7e,"nig wurde schwer verwundet und der junge Prinz entf",$7f,"hrt. Ich wollte sie aufhalten. Doch die ",$5f,"bermacht war zu gro",$7c,".",$a,"    ",$22,"Ihr habt mein Leben gerettet! Ich habe nichts, um Euch zu danken. Ich wurde von meinen Leuten im Kampf getrennt. Lasst Ihr mich mit Euch ziehen, um zusammen mein Volk zu suchen?",$22," ",0
_12: .byte "   ",$22,"Habt Ihr unser Angebot ",$7f,"berdacht? Uns allen w",$7d,"re geholfen, wenn ihr uns unterst",$7f,"tzt.",$22," ",0
_13: .byte "   Shindia wird klar, wie es um sie steht, und fleht um ihr Leben. ",$22,"Wartet! T",$7e,"tet mich nicht! Ich kann Euch wichtige Informationen geben! Ich wei",$7c,", wie Ihr den K",$7e,"nig retten k",$7e,"nnt! Das ist doch was wert, oder? Tot bin ich Euch nichts wert!",$22," ",0
_14: .byte "   In Todesangst erz",$7d,"hlt Shindia ihre Geschichte. ",$22,"Ich sehe, Ihr wisst von Xanathars Plan. Er entf",$7f,"hrte Prinz Keirgar, um Dunkelelfen und Zwerge gegeneinander aufzuhetzen.",$a,"    ",$22,"Da wir wussten, dass der K",$7e,"nig zu stur sein w",$7f,"rde, sich ",$7f,"berzeugen zu lassen, habe ich ihn vergiftet. Nur mit einem Trank, den ich in der Ebene unten im 'Raum der Schalter'",$22," versteckt habe, kann er aus seinem Koma gerettet werden",$22,".",$a,"    Bevor sie euch mehr sagen kann, wird das Team von tanzenden Lichtern am Ende des Gangs abgelenkt. Als Ihr Euch umseht, ist sie verschwunden. ",0
_15: .byte "   ",$22,"Also habt Ihr belanglosen S",$7e,"ldner der Herren von Waterdeep es trotz meiner Fallen bis hierher geschafft. Wie tragisch f",$7f,"r Euch.",$22,"",$a,"    ",$22,"Und wie schade f",$7f,"r mich. Ich habe es sehr genossen, Euch mit meinen Horden k",$7d,"mpfen und durch meine Fallen stolpern zu sehen. Nat",$7f,"rlich bin ich f",$7f,"r diese Fallen verantwortlich. Ebenso wie f",$7f,"r den Plan, Waterdeep unter meine absolute Kontrolle zu bringen!",$a,"    ",$22,"Eure Statistenrolle in meinem brillianten Plan ist nun vorbei. Ergebt Euch, und vielleicht werde ich Gnade zeigen.",$22," ",0
_16: .byte "   Eure Sicht verschwimmt. Ein Gef",$7f,"hl gro",$7c,"er Schw",$7d,"che ",$7f,"berkommt euch. Ihr f",$7f,"hlt Euch gezwungen, einige Gegest",$7d,"nde zur",$7f,"ck zu lassen. ",0
_17: .byte "   Eine Dunkelelfenpatroullie h",$7d,"lt Euch auf. Der Anf",$7f,"hrer sieht Euch ver",$7d,"chtlich an und knurrt: ",$22,"Nun, Trollfutter! Nennt mir einen Grund, warum ich Euch nicht zu den Sklaven werfen soll.",$22," ",0
_18: .byte "   ",$22,"Wie? Ihr wollt mich bestechen? Ich will kein Spielzeug sondern f",$7d,"hige Knechte. Egal welche Kreatur: Kenku, Kobolde, Troglodyten. Je j",$7f,"nger, desto einfacher sind sie zu brechen. Doch warum schw",$7d,"tze ich mit Euch? Haut ab oder wir schneiden Euch in Streifen!",$22," ",0
_19: .byte "   Der Anf",$7f,"hrer pr",$7f,"ft das Kenku-Ei eingehend. ",$22,"Ein bisschen jung, doch bestimmt n",$7f,"tzlich.",$a,"    Er wirft seinen dunklen Blick zur",$7f,"ck auf Euch. ",$22,"Gut, Ihr k",$7e,"nnt durch. Aber geht uns aus dem Weg!",$22,"",$a,"    Der Anf",$7f,"hrer der Patroullie nimmt alle Eurer Kenku-Eier und geht. ",0
_20: .byte "   Ihr seht eine dunkel bekleidete Figur. Z",$7f,"rst erstaunt, erkennt er Euch. ",$22,"Ach, Ihr. Waterdeeps Retter der Woche. Ihr habt ja keine Ahnung, wieviele schon vor Euch geschickt wurden, die Wahrheit ",$7f,"ber das B",$7e,"se im Untergrund herauszufinden. Na denn, Ihr gemieteten Erl",$7e,"ser. Lernt nun von meinem weiten und profunden Wissen.",$a,"    ",$22,"Xanathar hat Waterdeep seit Jahren unterwandert. Ist Waterdeep erst geschw",$7d,"cht genug, wird er seine Horden in den Kampf mit der ahnungslosen Stadt senden. Der einzige Weg Xanathar aufzuhalten w",$7d,"re, ihn zu t",$7e,"ten, doch ohne den Stab der Silvias ist es so gut wie unm",$7e,"glich.",$a,"    ",$22,"So weit ich wei",$7c,", besitzen die Zwerge dieses magische Artefakt. Doch sie wissen nicht, was es vermag. Die Dunkelelfen wissen von der Macht des Stabes. Doch nicht, dass er gegen Xanathar verwendet werden kann. Ihr seht, dass der Stab eine der wenigen Waffen ist, die dem Betrachter schaden k",$7e,"nnen, denn er wurde aus dem Stiel eines seiner Augen gefertigt.",$a,"    ",$22,"Dumme Dunkelelfen. Sie sollten Xanathars Verb",$7f,"ndete sein. Doch sie planen, die Zwerge auszul",$7e,"schen, den Stab zu stehlen und damit die Stadt zu ",$7f,"berfallen. Dies jedoch w",$7f,"rde die Herren von Waterdeep davon ",$7f,"berzeugen, wie gro",$7c," die Gefahr aus dem Untergrund ist und dadurch Xanathars Eroberung verz",$7e,"gern. Nun muss ich also die Dunkelelfen aufhalten und Silvias Stab f",$7f,"r mich bekommmen.",$a,"    ",$22,"Ihr seht, Freunde, ich habe nicht die Absicht, Xanathar aufzuhalten, bevor er Waterdeep erobert hat. Nach dem Streitzug wird er am schw",$7d,"chsten sein. Und dann schlage ich los.",$a,"    ",$22,"Xanathar wird in meiner Gnade und Waterdeep in meinen H",$7d,"nden sein. Ich kann nat",$7f,"rlich nicht zulassen, dass Ihr Xanathar von der Eroberung Waterdeeps abhaltet. Ich muss nur noch Silvias Stab bekommen... und Euch, ohne Frage, t",$7e,"ten.",$22," ",0
_21: .byte "   Ihr seht Prinz Keirgar, gefesselt. Er sieht Euch verzweifelt an. ",$22,"Bitte! Ihr m",$7f,"sst mich befreien! Ich muss zu meinem Clan um einen Krieg zwischen Zwergen und Dunkelelfen verhindern!",$22," ",0
_22: .byte "   Als sich Taghor Euch anschlie",$7c,"t, sagt er: ",$22,"Im Kampf habe ich den Feind ",$7f,"ber eine Treppe bis hier herauf verfolgt. Meine Leute sollten sich direkt unter uns befinden.",$22," ",0
_23: .byte "   Ein m",$7f,"der Zwergenkleriker spricht zu Euch: ",$22,"Ich helfe jedem der verletzt ist, doch meine Leute brauchen jetzt meine ganze Aufmerksamkeit. Aber, wenn Ihr uns helfen w",$7f,"rdet, den Prinzen zu finden...",$22," ",0
_24: .byte "   Die Zwerge bejubeln die R",$7f,"ckkehr ihres Prinzen. Der Kleriker und Krieger sammeln sich um ihn. Armun dreht sich zu Euch. ",$22,"Jenseits von Hoffnung seid Ihr mit Prinz Keirgar zur",$7f,"ckgekehrt. Wie k",$7e,"nnen wir Euch jemals danken?",$a,"    ",$22,"Sie wollen wissen, wie sie wieder hinauf kommen.",$22," unterbricht Keirgar. ",$22,"In Sagen ist von einem alten Thronsaal mit einer Geheimt",$7f,"r in der Nordwand die Rede. Sie f",$7f,"hrt in eine lange unterirdische Passage, die ",$7e,"stlich von Waterdeep endet.",$22," ",0
_25: .byte "   Prinz Keirgar sagt: ",$22,"Es muss etwas anderes geben, mit dem ich Euch belohnen kann. Das Mindeste, das ich f",$7f,"r Euch tun kann, ist Euch in Eurem Kampf gegen Xanathar beizustehen.",$22," ",0
_26: .byte "   Prinz Keirgar seufzt erleichtert: ",$22,"Habt Dank f",$7f,"r meine Rettung. Nun muss ich aber zu meinem Volk eilen, um sie zu warnen.",$a,"    ",$22,"Die Dunkelelfen hatten nichts mit meiner Entf",$7f,"hrung zu tun. Es war Xanathars Helferin Shindia. Sollten nun meine Leute versehentlich die Dunkelelfen bei der Suche nach mir angreifen, werden die Dunklen sie durch ihre ",$5f,"berzahl ausl",$7e,"schen.",$a,"    ",$22,"Und sucht mein Volk weiter nach unserer angestammten Heimat, werden sie in Xanathars Arme laufen. Wie ich aus Shindias Kommentaren entnommen habe, hat Xanathar sein Hauptquartier genau im Herzen unserer alten Stadt aufgebaut!",$a,"    ",$22,"Ich muss mein Vok finden und sie davon abhalten, die Dunklen oder Xanathar anzugreifen. Werdet Ihr mir beistehen, tapfere Abenteurer?",$22," ",0
_27: .byte "   ",$22,"Dies sollte den K",$7e,"nig erwecken!",$22," ruft Ihr als ihr dem Kleriker den Trank gebt. Skeptisch be",$7d,"ugt er die Flasche. Kurz darauf wacht K",$7e,"nig Teirgoh auf; noch sehr schwach, dennoch am Leben! ",$a,"    Eilig berichten ihm die Zwerge ",$7f,"ber die letzten Ereignisse, auch ",$7f,"ber Eure Beteiligung an seiner Erweckung.",$a,"    Bewegt dankt Euch der K",$7e,"nig. ",$22,"Tapfere Abenteurer. Ihr habt mein Leben gerettet. Bitte nehmt dies als unser wertvollstes Geschenk an. Ich wei",$7c," nicht viel dar",$7f,"ber. Nur, dass es Euch in Eurer dunkelsten Stunde weiterhelfen wird.",$22," ",0
_28: .byte "   Dorhum tritt dem Team bei. ",0
_29: .byte "   Widerwillig bleibt Dorhum bei seinen Leuten. ",0
_30: .byte "   Ihr t",$7e,"tet den hilflosen Zwerg. ",0
_31: .byte "   Anya ist verwirrt. ",$22,"Meine Gef",$7d,"hrten und ich starben im Kampf gegen Xanthars Horden. Ich dachte, ich w",$7f,"rde im Jenseits erwachen, nicht in den Gew",$7e,"lben, in denen ich fiel.",$22," ",$a,"    ",$22,"Es gef",$7d,"llt mir hier nicht, doch ich bin eine K",$7d,"mpferin. Ich werde Xanathar an eurer Seite jagen und den Tod meiner Kameraden r",$7d,"chen.",$22," ",0
_32: .byte "   ",$22,"Dann trennen sich unsere Wege. Ich werde allein Rache an Xanathar ",$7f,"ben. M",$7e,"ge Euch das Gl",$7f,"ck des J",$7d,"gers leiten.",$22," ",0
_33: .byte "   Beohram ist w",$7f,"tend. ",$22,"Wiedererweckt! Dann habe ich versagt. Ich bin Beohram von der Stadtwache. Als die ersten Ger",$7f,"chte ",$7f,"ber Xanathar aufkamen, stieg ich allein hinab um nachzusehen. Nun wei",$7c," ich, dass es mehr als Ger",$7f,"chte waren. Erlaubt Ihr mir, mit Euch meinen Kamp gegen das B",$7e,"se, das Waterdeep befallen hat, zu beenden?",$22," ",0
_34: .byte "   ",$22,"Ich bedaure es, nicht mit Euch zu ziehen, doch es ist Eure Entscheidung. Ich werde nun versuchen, meinen Weg nach oben zu finden, wo ich Eure edlen Taten im Angesicht der sicheren Verdammnis besingen werde.",$22," ",0
_35: .byte "   Kirath sieht sich ver",$7d,"rgert um. ",$22,"Ich soll tot gewesen sein? Ha! Ihr denkt wohl, ich schulde Euch jetzt was. E",$7f,"r Auftrag der Herren von Waterdeep ist mir egal, doch scheinbar haben wir denselben Weg.",$a,"    ",$22,"Ich bin Kirath, der gr",$7e,$7c,"te Zauberer des Reiches. Mich treibt die Suche nach Xanathar's Magie. Vielleicht k",$7e,"nnen wir einander helfen. Meine Talente und meine Macht k",$7e,"nnten Euch von Nutzen sein.",$22," ",0
_36: .byte "   ",$22,"Wie Ihr wollt. Ich bin wahrscheinlich besser dran, wenn Ihr mir nicht im Wege seid.",$22," ",0
_37: .byte "   Ileira jubelt: ",$22,"Die G",$7e,"tter seien gepriesen! Ich bin Schwester Ileira. Ich zog mit meinen Kameraden aus, hier unten das B",$7e,"se mit unserem Guten zu bek",$7d,"mpfen. Doch wir wurden ",$7f,"berw",$7d,"ltigt und die meisten von uns get",$7e,"tet.",$a,"    ",$22,"Ich wei",$7c,", dass ich diese zweite Chance dank meines Glaubens bekommen habe. Darf ich Euch begleiten? Meine Kraft als Heilerin kann Euch von gro",$7c,"er Hilfe sein.",$22," ",0
_38: .byte "   ",$22,"Dann muss ich meinen eigenen Weg finden. Lebt wohl, m",$7e,"ge das Licht Euch f",$7f,"hren.",$22," ",0
_39: .byte "   Tyrra sieht sich um. ",$22,"Na, toll! Ich werde umgebracht weil ich ein paar Narren hier nach unten gefolgt bin. Da kommen schon die N",$7d,"chsten und erwecken mich, damit ich einfach so mit ihnen ziehe!",$a,"    ",$22,"Wer sagt, dass ich ",$7f,"berhaupt hier sein will? Nat",$7f,"rlich k",$7e,"nnte ich Euch helfen, ich bin schlie",$7c,"lich eine ziemlich gute Waldl",$7d,"uferin. Doch wenn Ihr so tollk",$7f,"hn wie mein letztes Team seid, braucht Ihr mehr Hilfe als ich Euch geben kann.",$22," ",0
_40: .byte "   ",$22,"Also dann habt Ihr mich nur so aus Spa",$7c," wiedererweckt. Gut, geht schon. Geht. Mir recht. Macht was Ihr wollt. Ich finde hier auch so raus...",$22," ",0
_41: .byte "   Tod sieht sich m",$7f,"de um. ",$22,"Ich wei",$7c," nicht genau, wie ich hierher komme. Ihr sagt ich war tot. Ich erinnere mich, dass ich in einen Abwasserschacht fiel.",$a,"    ",$22,"Was gibt's da zu lachen? Ich bin ein ernsthafter Abenteurer, der schon viele wichtige Auftr",$7d,"ge erledigt hat. Habt Ihr nicht Verwendung f",$7f,"r einen gewitzten Dieb bei Euch?",$22," ",0
_42: .byte "   Der Halbling zuckt die Achseln. Er geht und murmelt: ",$22,"E",$7f,"r Pech...Spinner.",$22," ",0
_43: .byte "   Keirgar kommt zu Euch. ",0
_44: .byte "   Keirgar geht, um sein Volk zu suchen. ",0
_45: .byte "Auftrag und Ausweispapier:",$a,"Dies Dokument ist ein bindender Auftrag im Dienst der Herren und H",$7e,"chsten der Stadt Waterdeep. Die Inhaber dieses Schreibens sind Vertreter der Herren von Waterdeep, wodurch Ihnen volles Wegerecht unter der Stadt Waterdeep zusteht. Jede Einmischung wird den Zorn der Stadt Waterdeep nach sich ziehen.",$a,"Uns wurde zugetragen, dass eine Verschw",$7e,"rung in der Stadt im Gange ist. Spuren weisen zu den Abw",$7d,"ssern unter Waterdeep. Wir besitzen keine Informationen ",$7f,"ber die genaue Art der Gefahr, doch f",$7f,"hlen wir, dass Eile geboten ist. Hiermit beauftragen wir Euch, diese Gefahr zu finden und, wenn m",$7e,"glich, zu zerschlagen.",$a," Ihr erhaltet die vollen Rechte des Rates. Alle Sch",$7d,"tze, Artefakte und weiteren Wertgegenst",$7d,"nde seien Euer durch das Recht der Eroberung.",$a,"Dieses Schreiben ist rechtens und bindend durch unser Siegel am f",$7f,"nften Tage des Marpenoth im Jahr der Schatten. ",0
_46: .byte "   Das Sternenlicht funkelt im Edelstein. Folge einem, um den anderen zu sehen. ",0
_47: .byte "   Um den Hals",$a," aus Gold gemacht",$a," des Zwergen Zeichen",$a,", wie's Euch ",$7f,"berbracht ",0
_48: .byte "   Die Kugel f",$7f,"hrt zu gro",$7c,"em ",$5f,"bel. ",0
_49: .byte "   Die gr",$7e,"",$7c,"te Schw",$7d,"che der gef",$7f,"rchtetsten Kreatur ist, dass sie, obwohl in Schatten sich versteckt und alles sieht, sich nicht unsichtbar machen kann. ",0
_50: .byte "   Als sich das Team die ",$5f,"berreste von Xanathars zerschlagenem K",$7e,"rper ansieht, schaltet sich ein Teleporter ein. Als Xanathars Lager aus dem Blick verschwindet, bereiten sich alle auf einen Kampf vor und denken: ",$22,"Was kommt jetzt?",$22,"",$a,"    Ein stattlicher Raum aus Marmor erscheint um das Team. Zwei S",$7d,"ulen flankieren einen gro",$7c,"en Thron. Sonnenlicht str",$7e,"mt durch die Fenster. Saubere Luft weht durch eine offene T",$7f,"r. Dies ist der B",$7f,"rgersaal von Piergeiron. Endlich konnte das Team dem Verlies unter Waterdeep entrinnen!",$a,"    ",$22,"Ihr habt Xanathar get",$7e,"tet und Waterdeep von seinem ",$5f,"bel befreit!",$22," ruft Piergeiron Paladison aus. ",$22,"Wie weise waren wir, solch f",$7d,"hige und geschickte Abenteurer zu unseren Vertretern zu erw",$7d,"hlen. Lasst Euch heute als die Helden von Waterdeep feiern und lasst alle von Euren tapferen Taten wissen. Seid begl",$7f,"ckw",$7f,"nscht f",$7f,"r Euren Erfolg!",$22," ",0
_51: .byte "   Ihr seid geschlagen!",$a," Die Schergen des B",$7e,"sen k",$7e,"nnen ihre",$22," Pl",$7d,"ne ungehindert erf",$7f,"llen!",0

messages_lo: .byte <_00,<_01,<_02,<_03,<_04,<_05,<_06,<_07,<_08,<_09,<_10,<_11,<_12,<_13,<_14,<_15,<_16,<_17,<_18,<_19,<_20,<_21,<_22,<_23,<_24,<_25,<_26,<_27,<_28,<_29,<_30,<_31,<_32,<_33,<_34,<_35,<_36,<_37,<_38,<_39,<_40,<_41,<_42,<_43,<_44,<_45,<_46,<_47,<_48,<_49,<_50,<_51
messages_hi: .byte >_00,>_01,>_02,>_03,>_04,>_05,>_06,>_07,>_08,>_09,>_10,>_11,>_12,>_13,>_14,>_15,>_16,>_17,>_18,>_19,>_20,>_21,>_22,>_23,>_24,>_25,>_26,>_27,>_28,>_29,>_30,>_31,>_32,>_33,>_34,>_35,>_36,>_37,>_38,>_39,>_40,>_41,>_42,>_43,>_44,>_45,>_46,>_47,>_48,>_49,>_50,>_51
.include "../../text_resources.s"
