.segment "TEXTRESOURCES"

_00: .byte "   The dwarf gasps out, ",$22,"Drow... save the king... prince is gone...",$22," He falls unconscious. ",0
_01: .byte "   ",$22,"I thank you, but I will find my own way back. A warning: Beware the stone doorways set into these walls. They are portal entrances, which become active with the right key. My party encamped near such a portal, and was easily ambushed.",$22," Thanking you again, the dwarf wanders off. ",0
_02: .byte "   ",$22,"I am Armun, spokesman of this clan. Of course, we have information on the location of the exits from these halls, but in our hour of need, I have no time to help you. However, if you would be willing to help us...",$22," ",0
_03: .byte "   Armun begins, ",$22,"Our clan is descended from the dwarves who built these great halls. Here, our ancestors lived in peace, until hordes of evil creatures drove them out and into the realms of men and elves.",$a,"    ",$22,"On the surface, our numbers dwindled, finally, our leader, King Teirgoh, gathered our people and led us underground, in search of our ancestral home.",$a,"    ",$22,"Using secret knowledge, passed down through the royal family, we finally discovered these stone-carved halls. The halls were vast and we only explored a small portion before we had to make camp in an enclosed area decorated with a stone portal.",$a,"    ",$22,"But while the camp slept, the stone portal flared with magical light! From the light, a horde of drow charged us. They were led by a female they called Shindia.",$a,"    ",$22,"We rose up and fought the dark ones, though we were exhausted by long weeks of travel. Both sides suffered many casualties, but in the end, we forced them to retreat into the portal from which they came.",$a,"    ",$22,"The battle was costly. King Teirgoh was wounded by a poisoned dagger and now lies in eternal sleep. Nothing our cleric can do will wake him. His only son, Prince Keirgar, was captured by the invading drow. With no member of the royal family among us, we no longer have access to their secret knowledge of the exits from these halls.",$a,"    ",$22,"Now we wait, while our cleric heals our surviving warriors. Once prepared, we will try to rescue our prince and avenge the fall of Teirgoh. Our numbers are small, but we would rather fight to our deaths than abandon our prince to the drow.",$a,"    ",$22,"Unless... If your party were to rescue Prince Keirgar from the drow and return him to us, he could give you information about the exits from these halls. You would have your information and we would have our prince. So, will you help us?",$22," ",0
_04: .byte "   Armun's expression changes from expectant hope to sad disappointment. ",$22,"It's unfortunate that you cannot help us. We wish you well in your travels.",$22," ",0
_05: .byte "   Armun accepts your help with gratitude. He hands you a medallion made of stone. ",$22,"Take this. Shindia dropped it in the battle. It is the key to activate the portal through which she and her minions came.",$a,"    ",$22,"Our ancestors built the portals to transport them from one location to another quickly. When the portal doorway is touched with the right object, the portal is activated. We would have followed Shindia and her drow elves back through the portal, but we are not ready to confront them.",$a,"    ",$22,"The ancient ones also used powerful magic such as this to gain knowledge. Legend has it that there is an Oracle of Knowledge and the key to its operation is the powerful black orb. By placing an orb into the Oracle, its power is released.",$a,"    ",$22,"Our cleric can help heal your wounds. Be careful not to tax him too heavily; he has been healing the wounds of our warriors and trying to revive the king from his poisoned sleep.",$22," ",0
_06: .byte "   Armun stops you. ",$22,"One other thing: a young dwarven warrior would like to join you in your quest to find the prince.  Will you allow him to join you?",$22," ",0
_07: .byte "   An injured dwarf lies on the ground before you, nearly unconscious from his wounds. ",0
_08: .byte "   A weary dwarven cleric greets you. ",$22,"Yes, how can I help you?",$22," ",0
_09: .byte "   ",$22,"Whom shall I resurrect?",$22," ",0
_10: .byte "   An exhausted dwarven cleric rubs his eyes and tells you to come back after he has rested. ",0
_11: .byte "   Having regained his strength, the dwarf thanks you. ",$22,"I thought that I had met my death at the blade of that drow. In battle, our king was grievously wounded, and the young prince kidnapped. I tried to stop the drow, but alas, I was overcome.",$a,"    ",$22,"You have saved me from death! I wish there was some way to thank you, but I have nothing. I am alone, separated from my people during the battle. May I join you so that together we can search for my people?",$22," ",0
_12: .byte "   ",$22,"Have you reconsidered our offer? Both of our parties would benefit if you assist us.",$22," ",0
_13: .byte "   Shindia, suddenly realizing the odds, begs for her life. ",$22,"Wait! Please, don't kill me! Look, I know a lot, and I can give you important information! I can tell you how to save the king! That's worth something, isn't it?! I'm no good to you dead!",$22," ",0
_14: .byte "   Anxious to stay alive Shindia blurts her story. ",$22,"It's obvious you know of Xanathar's plot. He kidnapped Prince Keirgar to turn the drow and the dwarves against each other.",$a,"    ",$22,"Because we knew the king was too stubborn to brainwash, I poisoned him. The only way to revive him from his coma is with the potion that I stashed on the level below, in the 'Room of the Levers'",$22,".",$a,"    Before you can get any more information from Shindia, the party is distracted by a series of dancing lights far down the corridor. When the party turns back, she is gone. ",0
_15: .byte "   ",$22,"So, despite my traps, you petty hirelings of the Lords of Waterdeep managed to make it here after all. How unfortunate for you.",$22," ",$a,"    ",$22,"How sad for me as well. I enjoyed immensely watching you fight my minions and stumble through my traps. Of course, I'm responsible for creating the traps, just as I am responsible for creating the plan that will bring all of Waterdeep under my absolute control!",$a,"    ",$22,"You, of course, cannot be allowed to interfere with my brilliant plan. Surrender to me now, and perhaps I will grant you mercy.",$22," ",0
_16: .byte "   Your vision wavers. A feeling of incredible weakness washes over you. You feel compelled to drop some of your items. ",0
_17: .byte "   A drow patrol squad stops you from advancing. The patrol leader eyes you with contempt and snarls, ",$22,"Okay troll bait, give me one reason why I shouldn't run you to the slave pens.",$22," ",0
_18: .byte "   ",$22,"What? Are you trying to bribe or insult me? I don't want toys, I want potential servants. Any creature will do: kenku, kobolds, troglodytes. The younger they are, the easier they are to break in. But what am I rambling on to you for? Get out of here, or we'll run you through with our swords!",$22," ",0
_19: .byte "   The patrol leader hefts a kenku egg with approval. ",$22,"A bit young, but potentially useful.",$a,"    He turns his dark gaze back to you. ",$22,"All right, you can pass. But keep out of our way!",$22,"",$a,"    The drow patrol leader takes all the kenku eggs from your party and walks away. ",0
_20: .byte "   You interrupt a dark-robed figure. He's startled at first, then sneers in recognition. ",$22,"Oh, you. Waterdeep's saviors of the week. You don't realize how many other adventurers have been sent to find the truth about the evils underground. Well, rented redeemers, let me give you the benefit of my vast and profound knowledge.",$a,"    ",$22,"Xanathar has been undermining Waterdeep for years. When Waterdeep is sufficiently weakened, he will lead his minions in the conquest of the unsuspecting city. The only way to stop Xanathar is to kill him, and that would be virtually impossible without the wand of Silvias.",$a,"    ",$22,"As I understand it, the dwarves have the magical artifact, but they do not know what they possess. The drow knows that the Wand of Silvias is powerful, but not of its use against Xanathar.  You see the wand is one of the few magic items that can affect a beholder, because it is made from a beholder's eyestalk.",$a,"    ",$22,"Stupid drow. They're supposed to be Xanathar's allies, but they plan to finish off the dwarves, steal the wand, and use it to raid the city. This would alert the Lords of Waterdeep to the immensity of the threat from below ground and delay Xanathar's plans of conquest. So, I have to stop the drow and get the Wand of Silvias for myself.",$a,"    ",$22,"You see my friends, I have no intention of stopping Xanathar until he has completed the conquest of Waterdeep. After the conquest, Xanathar will be at his weakest. Only then will I strike.",$a,"    ",$22,"Xanathar will be at my mercy, and Waterdeep will be mine. So, I certainly can't let you keep Xanathar from conquering Waterdeep. I need only get the Wand of Silvias... and, of course, kill you.",$22," ",0
_21: .byte "   You see Prince Keirgar struggling against his bonds. He looks up at you with desperate hope. ",$22,"Please! You must free me! I need to return to my clan and avert the war between the dwarves and the drow!",$22," ",0
_22: .byte "   As Taghor joins your party he says, ",$22,"During the battle, I chased my enemy up a staircase, to this level. My people should be on the level just below us.",$22," ",0
_23: .byte "   A wary dwarven cleric eyes you and says, ",$22,"I would offer my help to anyone who is injured, but my people require immediate attention. Of course, if you were helping us in our efforts to find the prince...",$22," ",0
_24: .byte "   The dwarves rejoice at the return of their prince. Warriors and the cleric surround the prince. Armun turns to you. ",$22,"Beyond hope, you have returned with Prince Keirgar. How can we possibly thank you?",$a,"    ",$22,"They wish information on ways to surface,",$22," Keirgar interrupts. ",$22,"Lore has it there is an ancient throne room about seven levels down. In the throne room, there is a secret door in the north wall. The door opens to a long underground passageway, which should take you to the lands just east of Waterdeep.",$22," ",0
_25: .byte "   Prince Keirgar says, ",$22,"There must be some other way I can repay you for bringing me back to my people. The least I can do is continue to help you in your quest against Xanathar.",$22," ",0
_26: .byte "   Prince Keirgar sighs in relief, ",$22,"I thank thee, for the timely rescue. Now I must hurry to my people to warn them of two foul traps.",$a,"    ",$22,"First, the drow community was not behind my kidnapping. It was Xanathar's minion Shindia. If my people mistakenly attack the drow, in their search for me, the drow will annihilate them with superior numbers.",$a,"    ",$22,"Second, if my people continue their search for our ancestral home, they will run directly into Xanathar himself. I gather from Shindia's comments that Xanathar has set up his main quarters right in the heart of our ancient city!",$a,"    ",$22,"I must find my people and stop them from attacking the drow or assaulting Xanathar. Will you accompany me, brave adventurers?",$22," ",0
_27: .byte "   ",$22,"This should awaken the king!",$22,", you exclaim, as you give the potion to the cleric. Skeptically, the cleric administers the potion. A few moments later, King Teirgoh awakens, still weak but very much alive! ",$a,"    Quickly, the dwarves explain the past events to King Teirgoh, including your part in awakening him from the coma.",$a,"     Grateful, the king thanks you. ",$22,"Brave adventurers, you have saved my life. Please accept this, our most precious gift. I can tell you little about it, save only that it will aid you in your darkest hour.",$22," ",0
_28: .byte "   Dorhum joins the party. ",0
_29: .byte "   Dorhum reluctantly remains with his people. ",0
_30: .byte "   You kill the helpless dwarf. ",0
_31: .byte "   Anya looks about in confusion. ",$22,"My companions and I died fighting the minions of Xanathar. I expected to awaken in the afterlife, not in the dungeons where I had fallen.",$22," ",$a,"    ",$22,"I do not like this place, but I am a fighter. I would join you in your hunt for Xanathar so that I may avenge the deaths of my companions.",$22," ",0
_32: .byte "   ",$22,"Then, our paths must separate. I will exact my own revenge upon Xanathar. May the luck of the Hunter guide you.",$22," ",0
_33: .byte "   Beohram looks down in anger. ",$22,"Resurrected! Then my mission has failed. I am Beohram of the City Watch. When the rumors of Xanathar first arose, I went down alone to investigate. I see that they were more than rumors. Will you allow me to join you and finish my quest against the evil which plagues Waterdeep?",$22," ",0
_34: .byte "   ",$22,"I regret that I cannot accompany you to meet the threat. That decision is, of course, yours. I shall attempt to find my own route to the surface, where I will sing of your brave deeds in the face of certain doom.",$22," ",0
_35: .byte "   Kirath looks about, annoyed. ",$22,"You mean I was dead? Hmph. Now you probably think I owe you for resurrecting me. I care nothing for your commission from the Lords of Waterdeep, but we seem to be heading down the same path.",$a,"    ",$22,"I am Kirath, the greatest wizard of the Realms. I seek the special magics that Xanathar is alleged to possess. Perhaps we can help each other. At least, you might benefit from my talents and power.",$22," ",0
_36: .byte "   ",$22,"Have it your way. Like as not, I am probably better off without you getting in my way.",$22," ",0
_37: .byte "   Ileira looks about, jubilant. ",$22,"May the gods be praised! I am Sister Ileira. I journeyed with my comrades into these dungeons to fight evil and bring good. But we were overwhelmed, and most of us were killed.",$a,"    ",$22,"I see that because of my faith, I have been given another chance to carry on my mission of good. May I accompany you? My abilities to heal the wounded could be of great help.",$22," ",0
_38: .byte "   ",$22,"Then I must seek a path of my own. Fare thee well, and may the Light guide you.",$22," ",0
_39: .byte "   Tyrra takes in her surroundings. ",$22,"Oh, this is just great. I get killed following some fool party down here, and now another party comes by, resurrects me, and wants me to join up! Just like that!",$a,"    ",$22,"What makes you think I wanted to be here in the first place? Sure, I could probably help you; after all, I am a pretty good ranger. But if you're as foolhardy as the last party I followed, you'll need a lot more help than I can give you.",$22," ",0
_40: .byte "   ",$22,"So you resurrected me just for the fun of it. Sure, go ahead. Go. Fine with me. You do what you want. Me, I'm finding my own way out of here...",$22," ",0
_41: .byte "   Tod looks about warily. ",$22,"I...I'm not quite sure how it is I'm down here. You say I was dead. The last thing I remember was falling down into one of the sewage drains.",$a,"    ",$22,"Hey, it's not funny! I am a Serious Adventurer. I have been charged to complete many Important Quests. Perhaps you could find a use for a skilled rogue in your party?",$22," ",0
_42: .byte "   The halfling shrugs. As he wanders off, he mutters ",$22,"Your loss...fools.",$22," ",0
_43: .byte "   Keirgar joins the party. ",0
_44: .byte "   Keirgar wanders off in search of his people. ",0
_45: .byte "Commission and Letter of Marque:",$a,"This document is a binding commission of service to the Lords and sovereign city of Waterdeep. The bearers of this document are agents of the Lords of Waterdeep and are granted full rite of passage beneath the city of Waterdeep. Any, who would dare interfere risk the full penalty of our wrath.",$a,"Information has been presented to us that there is a plot afoot in our city. Evidence points to the sewers that run beneath Waterdeep. We have no information about the exact nature of the threat, but we feel the urgency is grave. We commission you to find the nature of the danger, and to destroy it if you are able.",$a,"You are granted full rights of marque. All treasures, artifacts, or other valuables are yours by right of conquest.",$a,"This writ is made legal and binding by our mark on this fifth day of Marpenoth in the year of Shadows. ",0
_46: .byte "   The light of the stars sparkles in the gem. Follow one to see the other. ",0
_47: .byte "   Around the neck",$a," made of gold",$a," the sign of Dwarves",$a," you've been told ",0
_48: .byte "   The orb leads to great evil. ",0
_49: .byte "   The greatest weakness of the most feared creature is that, although it lurks in shadows and sees all, it cannot make itself invisible. ",0
_50: .byte "   As the party picks through the remains of Xanathar's shattered body, a teleporter triggers about them. As Xanathar's lair fades from view, everyone prepares for battle and thinks, ",$22,"What now?",$22,"",$a,"    A stately marbled room fades in around the party.  Two stone columns flank a large throne. Sunlight streams in through the windows. Clean air blows in from an open door. This is Piergeiron's public hall! At last, the party is free from the dungeons under Waterdeep!",$a,"    ",$22,"You have killed Xanathar and saved Waterdeep from his evil!",$22," Piergeiron Paladinson exclaims. ",$22,"We were wise to pick such talented and resourceful adventurers as our agents. For today, let thee be proclaimed the Heroes of Waterdeep and let all know of your brave deeds! Congratulations on your successful quest!",$22," ",0
_51: .byte "All of your party has been defeated.",$a,"  The minions of evil will be able to carry out their plans unhindered!",0

messages_lo: .byte <_00,<_01,<_02,<_03,<_04,<_05,<_06,<_07,<_08,<_09,<_10,<_11,<_12,<_13,<_14,<_15,<_16,<_17,<_18,<_19,<_20,<_21,<_22,<_23,<_24,<_25,<_26,<_27,<_28,<_29,<_30,<_31,<_32,<_33,<_34,<_35,<_36,<_37,<_38,<_39,<_40,<_41,<_42,<_43,<_44,<_45,<_46,<_47,<_48,<_49,<_50,<_51
messages_hi: .byte >_00,>_01,>_02,>_03,>_04,>_05,>_06,>_07,>_08,>_09,>_10,>_11,>_12,>_13,>_14,>_15,>_16,>_17,>_18,>_19,>_20,>_21,>_22,>_23,>_24,>_25,>_26,>_27,>_28,>_29,>_30,>_31,>_32,>_33,>_34,>_35,>_36,>_37,>_38,>_39,>_40,>_41,>_42,>_43,>_44,>_45,>_46,>_47,>_48,>_49,>_50,>_51
.include "../../text_resources.s"
